site_name: 'Prácticas DWEC'
site_description: 'Port of the Read the Docs theme to Jekyll to use with GitHub Pages.'
repo_url: 'https://github.com/vgonzalez165/dwec'
repo_name: 'GitHub'
docs_dir: 'docs/'
site_dir: '_site_mkdocs/'
theme: 'readthedocs'
prev_next_buttons_location: 'both'
copyright: 'Victor J. González Rodríguez'