title: Prácticas de Desarrollo Web en Entorno Cliente
description: Prácticas del módulo DWEC del CFGS Desarrollo de Aplicaciones Web
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Víctor J. González Rodríguez
repo_url: "https://github.com/vgonzalez165/dwec"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
